AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Resources:
  CommentValidator:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/comment_validator.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
        StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
        StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
        ChallengeEmailFunctionArn: !GetAtt ChallengeEmailFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False
            Schedule: 'rate(1 hour)'
        CommentAPIEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CommentApi
            Path: /comments/
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ChallengeEmailFunction
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  CommentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false

  StockCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_checker/
      Handler: app.lambda_handler
      Runtime: python3.9

  ChallengeEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/challenge_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - SESCrudPolicy:
            IdentityName: 'jamesshapirocomments+athens@gmail.com'

  ConfirmEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/confirm_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Role: !GetAtt ConfirmEmailRole.Arn
      Events:
        CommentAPIEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CommentApi
            Path: /comments/
            Method: get

  ConfirmEmailRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:SendTaskSuccess
                Resource: !Ref CommentValidator

  # SubmitCommentFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/submit_comment/
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Timeout: 30
  #     Policies:
  #       - StepFunctionsExecutionPolicy:
  #           StateMachineName: !GetAtt CommentValidator.Name
  #     Environment:
  #       Variables:
  #         STATE_MACHINE_ARN: !Ref CommentValidator
  #     Events:
  #       CommentAPIEvent:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref CommentApi
  #           Path: /comments/
  #           Method: post

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_seller/
      Handler: app.lambda_handler
      Runtime: python3.9

  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_buyer/
      Handler: app.lambda_handler
      Runtime: python3.9

  TransactionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  #######################################################
  ##### Start of Custom functions #####
  #######################################################
  ValueFuncExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:UpdateFunctionConfiguration
                Resource: !GetAtt ChallengeEmailFunction.Arn

  ValueFunc:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os
          def lambda_handler(event, context):
            response_code = 200
            lambda_client = boto3.client('lambda')
            confirm_comment_endpoint = os.environ['CONFIRM_COMMENT_ENDPOINT']
            function_name = os.environ['FUNCTION_NAME']
            response = lambda_client.update_function_configuration(
              FunctionName=function_name,
              Environment={
                'Variables': {
                    'CONFIRM_COMMENT_ENDPOINT': confirm_comment_endpoint
                }
              }
            )
            responseData = {}
            responseData['Data'] = 'SUCCESS'
            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "CustomResourcePhysicalID", noEcho=True)
      Handler: index.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ValueFuncExecutionRole}'
      Environment:
        Variables:
          CONFIRM_COMMENT_ENDPOINT: !Sub 'https://${CommentApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/comments/'
          FUNCTION_NAME: !Ref ChallengeEmailFunction
  GetLambdaFunctionWasUpdatedValue:
    Type: Custom::LambdaCallout
    Properties:
      ServiceToken: !GetAtt ValueFunc.Arn
      ChallengeEmailFunction: !Ref ChallengeEmailFunction
      #ApiKeyID: !Ref JournalEntryApiKey

Outputs:
  CommentValidatorArn:
    Description: 'Stock Trading State machine ARN'
    Value: !Ref CommentValidator
  CommentValidatorRoleArn:
    Description: 'IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates'
    Value: !GetAtt CommentValidatorRole.Arn
  CommentApiEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage for Comment Approval Workflow operations'
    Value: !Sub 'https://${CommentApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/comments/'
  LambdaFunctionUpdatedValue:
    Description: 'Was the Lambda Function updated?'
    Value: !GetAtt GetLambdaFunctionWasUpdatedValue.Data
