AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Resources:
  CommentValidator:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/comment_validator.asl.json
      DefinitionSubstitutions:
        ChallengeCommenterEmailFunctionArn: !GetAtt ChallengeCommenterEmailFunction.Arn
        ChallengeModeratorEmailFunctionArn: !GetAtt ChallengeModeratorEmailFunction.Arn
        GenerateUlidFunctionArn: !GetAtt GenerateUlidFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBUpdateItem: !Sub arn:${AWS::Partition}:states:::dynamodb:updateItem
        CommentsDDBTable: !Ref CommentsDDBTable
      Events:
        CommentApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CommentApi
            Path: /entry-point/
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ChallengeCommenterEmailFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateUlidFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ChallengeModeratorEmailFunction
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentsDDBTable

  CommentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false

  ConfirmCommenterApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt CommentApi.RootResourceId
      PathPart: commenter-confirmation
      RestApiId: !Ref CommentApi

  ConfirmModeratorApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt CommentApi.RootResourceId
      PathPart: moderator-confirmation
      RestApiId: !Ref CommentApi

  ConfirmCommenterApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: production
      RestApiId: !Ref CommentApi
      StageName: production
    DependsOn:
      - ConfirmCommenterApiMethod
      - ConfirmModeratorApiMethod

  ConfirmCommentApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:SendTaskSuccess
                Resource: !Ref CommentValidator

  ConfirmCommenterApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: 'GET'
      AuthorizationType: 'NONE'
      RequestParameters:
        method.request.querystring.token: true
      Integration:
        Type: AWS
        Uri: 'arn:aws:apigateway:us-east-1:states:action/SendTaskSuccess'
        IntegrationHttpMethod: 'POST'
        PassthroughBehavior: 'WHEN_NO_TEMPLATES'
        RequestTemplates:
          #'application/json': '{"taskToken": "$input.params(''token'')"}'
          #'application/json': '{"output": "[\"SUCCESS\"]", "taskToken": "$input.params(''token'')"}'
          'application/json': '{"output": "{\"decision\": \"confirm\", \"comment_ulid\": \"DUMMY#ULID\"}", "taskToken": "$input.params(''token'')"}'

        Credentials: !GetAtt ConfirmCommentApiRole.Arn
      RestApiId: !Ref CommentApi
      ResourceId: !Ref ConfirmCommenterApiResource

  ConfirmModeratorApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: 'GET'
      AuthorizationType: 'NONE'
      RequestParameters:
        method.request.querystring.token: true
      Integration:
        Type: AWS
        Uri: 'arn:aws:apigateway:us-east-1:states:action/SendTaskSuccess'
        IntegrationHttpMethod: 'POST'
        PassthroughBehavior: 'WHEN_NO_TEMPLATES'
        RequestTemplates:
          #'application/json': '{"taskToken": "$input.params(''token'')"}'
          #'application/json': '{"output": "[\"SUCCESS\"]", "taskToken": "$input.params(''token'')"}'
          'application/json': '{"output": "{\"decision\": \"confirm\", \"comment_ulid\": \"DUMMY#ULID\"}", "taskToken": "$input.params(''token'')"}'

        Credentials: !GetAtt ConfirmCommentApiRole.Arn
      RestApiId: !Ref CommentApi
      ResourceId: !Ref ConfirmModeratorApiResource

  ChallengeCommenterEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/challenge_commenter_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        # TODO: parameterize
        - DynamoDBWritePolicy:
            TableName: !Ref CommentsDDBTable
        - SESCrudPolicy:
            IdentityName: 'jamesshapirocomments+athens@gmail.com'

  GenerateUlidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/generate_ulid/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30

  ChallengeModeratorEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/challenge_moderator_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        # TODO: parameterize
        - SESCrudPolicy:
            IdentityName: 'jamesshapirocomments+athens@gmail.com'

  CommentsDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'PK1'
          AttributeType: 'S'
        - AttributeName: 'SK1'
          AttributeType: 'S'
        - AttributeName: 'GSI1PK'
          AttributeType: 'S'
        - AttributeName: 'GSI1SK'
          AttributeType: 'S'
      BillingMode: 'PAY_PER_REQUEST'
      KeySchema:
        - AttributeName: 'PK1'
          KeyType: 'HASH'
        - AttributeName: 'SK1'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'GSI1'
          KeySchema:
            - AttributeName: 'GSI1PK'
              KeyType: 'HASH'
            - AttributeName: 'GSI1SK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'

  #######################################################
  ##### Start of Custom functions #####
  #######################################################
  ValueFuncExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:UpdateFunctionConfiguration
                Resource:
                  - !GetAtt ChallengeCommenterEmailFunction.Arn
                  - !GetAtt ChallengeModeratorEmailFunction.Arn

  ValueFunc:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os
          def lambda_handler(event, context):
            responseData = {}
            try:
              response_code = 200
              lambda_client = boto3.client('lambda')
              confirm_commenter_endpoint = os.environ['CONFIRM_COMMENTER_ENDPOINT']
              confirm_moderator_endpoint = os.environ['CONFIRM_MODERATOR_ENDPOINT']
              confirm_commenter_function_name = os.environ['CONFIRM_COMMENTER_FUNCTION_NAME']
              confirm_moderator_function_name = os.environ['CONFIRM_MODERATOR_FUNCTION_NAME']
              endpoints = [confirm_commenter_endpoint, confirm_moderator_endpoint]
              function_names = [confirm_commenter_function_name, confirm_moderator_function_name]
              for endpoint, function_name in zip(endpoints, function_names):
                print(endpoint, function_name)
                response = lambda_client.update_function_configuration(
                  FunctionName=function_name,
                  Environment={
                    'Variables': {
                        'CONFIRMATION_ENDPOINT': endpoint
                    }
                  }
                )
              responseData['Data'] = 'SUCCESS3'
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "CustomResourcePhysicalID", noEcho=True)
            except:
              responseData['Data'] = 'FAILURE'
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData, "CustomResourcePhysicalID" )
      Handler: index.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ValueFuncExecutionRole}'
      Environment:
        Variables:
          CONFIRM_COMMENTER_ENDPOINT: !Sub 'https://${CommentApi}.execute-api.${AWS::Region}.amazonaws.com/production/commenter-confirmation/'
          CONFIRM_MODERATOR_ENDPOINT: !Sub 'https://${CommentApi}.execute-api.${AWS::Region}.amazonaws.com/production/moderator-confirmation/'
          CONFIRM_COMMENTER_FUNCTION_NAME: !Ref ChallengeCommenterEmailFunction
          CONFIRM_MODERATOR_FUNCTION_NAME: !Ref ChallengeModeratorEmailFunction
  GetLambdaFunctionWasUpdatedValue:
    Type: Custom::LambdaCallout
    Properties:
      ServiceToken: !GetAtt ValueFunc.Arn
      ChallengeCommenterEmailFunction: !Ref ChallengeCommenterEmailFunction
      ChallengeModeratorEmailFunction: !Ref ChallengeModeratorEmailFunction

Outputs:
  EntryPointApiEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage for Comment Approval Workflow operations'
    Value: !Sub 'https://${CommentApi}.execute-api.${AWS::Region}.amazonaws.com/production/entry-point/'
  LambdaFunctionUpdatedValue:
    Description: 'Was the Lambda Function updated?'
    Value: !GetAtt GetLambdaFunctionWasUpdatedValue.Data
